project:
  type: "website"
  title: "LSE DS105M 2022/23"
  output-dir: _output
  render:
    - "index.qmd"
    - "assessments.qmd"
    - "syllabus.qmd"
    - "export_syllabus.qmd"
    - "communication.qmd"
    - "weeks/*.qmd"
    - "weeks/week01/*.qmd"
    - "weeks/week02/*.qmd"
    - "slides/*.qmd"

bibliography: references/references.bib
csl: references/chicago-author-date.csl

website:
  title: "LSE DS105M 2022/23"
  repo-url: https://github.com/LSE-DSI/lse-ds105-course-notes
  page-navigation: true
  reader-mode: true
  favicon: "/figures/LSE Data Science Institute.png"
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "ğŸ  Home"
      - href: syllabus.qmd
        text: "ğŸ““ Syllabus"
      - href: communication.qmd
        text: "ğŸ“Ÿ Communication"
      - href: assessments.qmd
        text: "âœï¸ Assessments"
      - section: "ğŸ—“ï¸ Weeks"
        contents:
         - href: weeks/week01.qmd
           text: Week 01
           contents:
             - href: weeks/week01/lecture.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Slides
             - href: weeks/week01/prep.qmd
               text: ğŸ“’ Prepare for the lab
             - href: weeks/week01/lab.qmd   
         - href: weeks/week02.qmd
           text: Week 02
           contents:
             - href: weeks/week02/lecture.qmd
               text: ğŸ‘¨â€ğŸ« Lecture Slides
             - href: weeks/week02/prep.qmd
               text: ğŸ“’ Prepare for the lab
             - href: weeks/week02/lab.qmd
               text: ğŸ’» Lab roadmap
             - href: weeks/week02/appendix.html
               text: ğŸ”– Appendix
  navbar:
    background: primary
  page-footer:
    background: light
    left: "Copyright 2022, LSE Data Science Institute" 
    right: 
      - icon: mailbox 
        href: mailto:DSI.Admin@lse.ac.uk
      - icon: twitter 
        href: https://twitter.com/lsedatascience
  
format:
  html:
    subtitle: "DS105 - Data for Data Science"
    email-obfuscation: javascript
    link-external-newwindow: true
    link-external-icon: true
    link-external-filter: ^(?:http:|https:)\/\/(?:lse-dsi\.github\.io\/|localhost)
    author: Dr. [Jon Cardoso-Silva](https://www.lse.ac.uk/DSI/People/Jonathan-Cardoso-Silva)
    author-meta: Dr. Jon Cardoso-Silva
    date-format: "DD MMMM YYYY"
    theme:
      light: journal
      dark:  darkly
    css: custom_style.css
    toc: true

margin-header: |
 ![](/figures/LSE Data Science Institute.png)

body-header: |
  Experimenting
